language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_install:
  - export PATH=./node_modules/.bin/:$PATH
  - npm install -g node-gyp
  - npm install -g npm
install:
    - npm install
branches:
  only:
    - master
notifications:
  recipients:
    - mv@verman.fr
    - mf@verman.fr
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#gatejs"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
env:
  - LANG="en_US.UTF-8"
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
os:
  - linux
  - osx
sudo: required
dist: xenial
