language: node_js
node_js:
  - "4"
before_install:
  - "npm config set spin false"
  - "npm install -g npm"
install:
    - npm install
branches:
  only:
    - master
notifications:
  recipients:
    - mv@verman.fr
    - mf@verman.fr
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#gatejs"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
env:
  - LANG="en_US.UTF-8"
os:
  - linux
  - osx
sudo: required
dist: trusty
